# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

stages:
  - test
  - build
  - publish

# rules -----------------------------------------------------------------------

.code-patterns: &code-patterns
  - "src/**/*"
  - ".gitlab-ci.yml"
  - "conftest.py"
  - "pyproject.toml"
  - "uv.lock"

.rule:code-merge-request-manual: &rule-code-merge-request-manual
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  changes: *code-patterns
  when: manual

.rule:code-default-branch-manual: &rule-code-default-branch-manual
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  changes: *code-patterns
  when: manual

.rule:default-branch-manual: &rule-default-branch-manual
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  when: manual

.rule:on-tag: &rule-on-tag
  if: '$CI_COMMIT_TAG'

# jobs ------------------------------------------------------------------------

lint:
  stage: test
  image: ghcr.io/astral-sh/ruff:alpine
  rules:
    - *rule-code-merge-request-manual
    - *rule-code-default-branch-manual
  dependencies: []
  interruptible: true
  allow_failure: true
  variables:
    FORCE_COLOR: 1
  script:
    - ruff check --output-format gitlab --output-file codequality.json --exit-zero
    - ruff check --output-format concise
  artifacts:
    when: always
    reports:
      codequality: codequality.json

format:
  stage: test
  rules:
    - *rule-code-merge-request-manual
    - *rule-code-default-branch-manual
  image: ghcr.io/astral-sh/ruff:alpine
  dependencies: []
  interruptible: true
  allow_failure: true
  variables:
    FORCE_COLOR: 1
  script:
    - ruff format --check --output-format gitlab > codequality.json || true
    - ruff format --check --output-format full
  artifacts:
    when: always
    reports:
      codequality: codequality.json

mypy:
  stage: test
  rules:
    - *rule-code-merge-request-manual
    - *rule-code-default-branch-manual
  image: ghcr.io/astral-sh/uv:python3.14-alpine
  dependencies: []
  interruptible: true
  allow_failure: true
  variables:
    FORCE_COLOR: 1
    TERM: ansi # https://github.com/python/mypy/issues/13817
    SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TYPES_MAYA: "0.0.0"
  script:
    - uv sync --group dev
    - uv run --no-sync -m mypy --output json > mypy-report.json || true
    - uvx mypy-gitlab-code-quality < mypy-report.json > codequality.json
    - uv run --no-sync -m mypy
  artifacts:
    when: always
    reports:
      codequality: codequality.json

pyright:
  stage: test
  rules:
    - *rule-code-merge-request-manual
    - *rule-code-default-branch-manual
  image: node:24-alpine3.21
  dependencies: []
  interruptible: true
  allow_failure: true
  variables:
    FORCE_COLOR: 1
    TERM: ansi # https://github.com/python/mypy/issues/13817
  script:
    - npm install --global pyright pyright-to-gitlab-ci
    - pyright --outputjson > pyright-report.json || true
    - pyright-to-gitlab-ci --src pyright-report.json --output codequality.json --base_path .
    - pyright
  artifacts:
    when: always
    reports:
      codequality: codequality.json

ty:
  stage: test
  rules:
    - *rule-code-merge-request-manual
    - *rule-code-default-branch-manual
  image: ghcr.io/astral-sh/uv:python3.14-alpine
  dependencies: []
  interruptible: true
  allow_failure: true
  variables:
    FORCE_COLOR: 1
  script:
    - uvx ty check --output-format gitlab --exit-zero > codequality.json
    - uvx ty check --output-format concise
  artifacts:
    when: always
    reports:
      codequality: codequality.json

# TOOD(tga): pyrefly

package:
  stage: build
  rules:
    - *rule-on-tag
    - <<: *rule-default-branch-manual
      needs: []
  image: ghcr.io/astral-sh/uv:python3.14-trixie
  interruptible: true
  variables:
    ATTEST_BUILD_ARTIFACTS: true # TODO(tga): experimental
  script: # derived from: https://github.com/hynek/build-and-inspect-python-package
    # the '.gitignore' litters the provenance attestation
    - uv build --clear --no-create-gitignore --out-dir dist
    - uvx check-wheel-contents dist/*.whl
    - uvx twine check --strict dist/*
  artifacts:
    paths: ["dist/"]

pypi:
  stage: publish
  rules:
    - *rule-on-tag
  image: ghcr.io/astral-sh/uv:alpine
  dependencies: [package]
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script: uv publish

test-pypi:
  stage: publish
  rules:
    - *rule-default-branch-manual
  image: ghcr.io/astral-sh/uv:alpine
  dependencies: [package]
  id_tokens:
    TESTPYPI_ID_TOKEN:
      aud: testpypi
  variables:
    UV_PUBLISH_URL: https://test.pypi.org/legacy/
  script: uv publish

gitlab-release:
  stage: publish
  rules:
    - *rule-on-tag
  needs: ["pypi"]
  image: registry.gitlab.com/gitlab-org/cli:latest # alpine
  script:
    - apk update && apk add --no-cache git curl
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uvx hed --softbreak --tag "$CI_COMMIT_TAG" > RELEASE.md
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "$CI_COMMIT_TAG"
    description: "RELEASE.md"
